### ISSUE TITLE
pdos sum =/ total dos

### ISSUE THREAD

**Issue by KwonSnow** [QijingZheng/pyband#19]
Dear Dr. Zheng,

When I plot the all pdos which cover all atoms in the system,
it does not look like pdos sum equals to total dos.
The ranges, 0.5 ~ 1 eV and 2 ~ 2.5 eV, are especially noticeable. 
or is there any known issue for decomposing the total dos into pdos?
![dos_total](https://user-images.githubusercontent.com/44598071/85813119-405a1e00-b717-11ea-9edb-fd8bf21ca6b8.png)

Any help would be greatly appreciated!
Thank you!

Best regards,
Soonho

**Comment by QijingZheng** [comment]
Hi Sooho

The discrepancy between the pdos sum and the total dos is due to the fact that the "tot" in PROCAR is not equal to 1.0, in fact the "tot" is always <= 1.0. 

The total dos is defined as TDOS(E) = \sum_{n} \delta(E - En), where "n" is the state index and the \delta function is often substituted by a smearing function, e.g. a gaussian or a Lorentz distribution function. On the other hand, the atoms-decomposed dos, i.e. pdos in my scripts, is defined as PDOS(E) = \sum_{n} w_a \delta(E - En), in which the weight "w_a" is obtained from PROCAR and indicates the contribution of the selected atoms to the state "n". As a result, when you sum the PDOS over all the atoms, you sum the weight "w_a", which is often not equal to 1.0 and hence the difference between the TDOS and PDOS sum.

Best
Qijing

**Comment by KwonSnow** [comment]
Thank you for your kind explanation.
It helps a lot for understanding this mismatch.
I hope you stay well and healthy!

Sincerely,
Soonho
